QUERY_GROUPS = {
    "organizations": [
        "Proud Boys", "Oath Keepers",
        "America First", "Quick Reaction Force", "QRF",
        "Stop Steal", "Stop Steel", "War Room",
        "federal agent",
    ],
    "key_people": [
        "Tarrio", "Nordean", "Rehl", "Chesebro", "Eastman", "Giuliani",
        "Meadows", "Hutchinson", "Epps", "Donoghue", "Raffensperger",
        "Epshteyn", "Pezzola", "Harrelson", "Vallejo", "Babbitt",
        "Sicknick", "Cipollone", "Ornato", "Cheatle", "McDaniel",
        "Cawthorn", "Tuberville", "McInnes", "DSouza",
        "Pierson", "Ducey", "Stirewalt", "Stepien",
        "Stewart Rhodes", "Kelly Meggs", "Joe Biggs", "Sidney Powell",
        "Jeffrey Clark", "Jeffrey Rosen", "Bill Barr", "William Barr",
        "Ruby Freeman", "Shaye Moss", "Mike Pence", "Roger Stone",
        "Steve Bannon", "Ali Alexander", "Peter Navarro", "Joshua James",
        "Jessica Watkins", "Eugene Goodman", "Greg Jacob", "Marc Short",
        "Mo Brooks", "Jim Jordan", "Josh Hawley",
        "Kevin McCarthy", "Scott Perry", "Rupert Murdoch",
        "Ken Block", "Jason Miller", "Alex Cannon", "Matthew Morgan",
        "Brian Kemp", "Jack Smith",
        "Kushner", "Conway", "Scavino", "Chansley", "Boyland", "Greeson", "Phillips",
    ],
    "legal_schemes": [
        "fake electors", "alternate electors", "false electors",
        "elector scheme", "elector plot", "elector slates", "electoral slate",
        "Electoral Count", "seditious conspiracy", "conspiracy",
        "decertify", "NARA", "ascertainment",
    ],
    "key_events_specific": [
        "January 6", "Jan 6", "j6", "Ellipse", "Save America",
        "Capitol", "Rotunda", "pipe bomb", "trial by combat",
        "stand back", "stand by",
        "fight hell", "be wild",
        "see you in DC", "Mike deserves", "send it back", "hell break loose",
        "calvary", "courage and spine", "torches and pitchforks",
        "peaceful and patriotically", "go to the mattresses",
        "American revolution", "election corrupt",
        "elite strike force", "brain room", "surrender caucus", "death spiral",
        "1776 Returns", "Lexington", "Charlottesville",
        "Unite the Right", "Heather Heyer", "Pennsylvania Avenue",
        "Speakers Lobby", "Senate chambers", "Rotunda doors",
        "mags away", "january 3rd", "jan 3rd",
    ],
    "key_events_broad": [
        "insurrection", "coup", "certification", "certify", "electoral vote",
        "joint session",
        "187 minutes", "transfer power",
        "body armor", "magnetometers", "phones wiped", "Signal chat",
        "QAnon", "q anon", "Antifa",
    ],
    "fraud_claims": [
        "Dominion", "rigged election", "stolen election",
        "stop count", "mail in ballot", "absentee ballot",
        "drop box", "signature verification", "ballot harvesting", "2000 Mules",
        "State Farm Arena", "suitcase ballots", "ballots table", "vote dump",
        "votes voters", "dead voters", "state voters",
        "find votes", "11780", "blue shift", "Antrim County",
        "Wayne County", "Fulton County", "recount",
        "Hugo Chavez", "ASOG", "fraud commission", "mass resignations",
    ],
    "legal_proceedings": [
        "Lost Stolen", "64 cases",
        "select committee", "Fox News", "Giuliani defamation",
        "Giuliani bankruptcy", "Trump indicted",
        "Oval Office", "Stephanos Bibas",
        "Brett Ludwig", "Salem Media",
    ],
    "key_documents": [
        "Hutchinson testimony", "Meadows texts", "Donoghue notes",
        "Clark letter", "Pence card",
        "indictment", "court filing", "deposition",
    ],
    "figures_and_media": [
        "Glenn Greenwald", "Alex Jones", "Tucker Carlson", "Krystal Ball",
        "Owen Shroyer", "Fox News", "OAN",
        "Newsmax", "Epoch Times",
    ],
    "downplaying_narratives": [
        "fed posting", "let them in",
        "agent provocateur", "false flag",
        "Jacob Chansley",
    ],
    "schizo_arc": [
        "demonetized",
        "Elon replied", "Elon responded", "Elon tweet",
        "doxx",
        "thumb scale",
        "appropriate advertisers",
        "End Wokeness",
        "not Elon", "melt brain", "sound Elon",
        "legal liability",
        "bot accounts", "fake account",
        "real person", "real account",
        "CyberVegan",
        "destiny13337",
        "geolocate",
        "account created", "IP address",
        "same picture", "tweet each other",
        "Chilakian", "Chilokian", "Shellakian", "Chileian",
        "Aegon", "Egon", "egon cholakian", "Alon Egon",
        "intelligence educator", "clandestine service",
        "Earth Save", "govinfo.gov",
        "Creative Society", "Alatra", "Elantre",
        "Baby Poppy", "Hope Summers",
        "federal court",
        "Foreign Agent",
        "EI PressWire",
        "babel.ua",
        "Katanada", "Katrina Panova",
        "pro-Russian sect", "Russian penetration",
        "Tim Pool", "persona non grata",
        "glorifying terrorism", "Kick ban",
        "firefighter",
        "schizophrenic", "schizo", "schizoposting",
        "gang stalking",
        "going deeper",
        "pull lever", "push lever",
        "russia gate", "russian bot",
    ],
}

REACTION_TERMS = [
    "holy shit", "what the fuck", "my god", "oh shit",
    "actual fuck", "fucking shot", "no shot",
    "christ",
    "didn't know", "no idea", "didn't realize", "never knew",
    "wasn't aware", "not aware",
    "never heard", "never seen", "first time seeing",
    "news to me", "how not know", "how did we not know",
    "nobody talks", "nobody tell",
    "moving position",
    "i'm curious",
    "now i'm less sure",
    "wait a second", "hold on",
    "wait what", "bro what",
    "this is insane", "this is crazy", "unhinged",
    "that's crazy",
    "gangster shit", "kind of insane",
    "genuinely insane", "probably the most",
    "actually fucking",
    "crazy bro", "insane bro",
    "are you kidding", "kidding me", "can't be right", "how is that possible",
    "losing my mind",
]
